### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by zainafzal09** [saks-am/Selenium-Automation#1]
I tried you LinkedIn, there was no account. 
How can i contact you?

**Comment by saks-am** [comment]
Heyy! I have updated the link to my LinkedIn profile on the Readme file.
Please feel free to connect with me now and i regret for the link not
working earlier.

This is the link for more ease:
https://www.linkedin.com/in/saksham-sahu-2170b1193

**Comment by zainafzal09** [comment]
Can i get your whatsapp number? Or fb profile?

**Comment by zainafzal09** [comment]
It's showing premium on massage options

**Comment by saks-am** [comment]
I have pinged you on LinkedIn, hope it helps.
